[package]
name = "xdump"
version = "0.2.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
goblin = "0.8.2"
iced-x86 = "1.21.0"
regex = "1.10.4"
clap = "4.5.4"
chrono = "0.4.38"

[profile.release]
# strip = true
# opt-level = 3
# codegen-units = 1
# panic = "abort"
# lto = true
